# Generated by Django 4.0.3 on 2022-03-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_card_number', models.CharField(blank=True, max_length=100, null=True)),
                ('job_card_client', models.CharField(blank=True, max_length=100, null=True)),
                ('job_card_requester', models.CharField(blank=True, max_length=100, null=True)),
                ('job_card_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('job_card_location', models.CharField(blank=True, max_length=100, null=True)),
                ('job_card_created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card_started_at', models.DateTimeField(blank=True, null=True)),
                ('Job_card_completed_at', models.DateTimeField(blank=True, null=True)),
                ('job_card_technician', models.CharField(blank=True, max_length=100, null=True)),
                ('job_card_type', models.CharField(blank=True, max_length=100, null=True)),
                ('job_card_status', models.CharField(blank=True, max_length=100, null=True)),
                ('job_card_description', models.TextField(blank=True, null=True)),
                ('job_card_priority', models.CharField(blank=True, default='Normal', max_length=100, null=True)),
                ('job_card_resolution', models.TextField(blank=True, null=True)),
                ('job_card_completion_description', models.CharField(blank=True, max_length=100, null=True)),
                ('job_card_nva_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
