# Generated by Django 4.0.4 on 2022-04-28 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iSmartcoApp', '0002_remove_jobcard_job_card_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='job_category',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='job_card_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='job_card_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='job_card_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='job_card_priority',
            field=models.CharField(blank=True, default='Normal', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='job_card_requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
