# Generated by Django 4.0.3 on 2022-04-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iSmartcoApp', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id_num',
            field=models.CharField(max_length=13),
        ),
    ]
