# Generated by Django 4.0.4 on 2022-04-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iSmartcoApp', '0003_remove_employee_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(1, 'sysAdmin'), (2, 'CompAdmin'), (3, 'Client'), (4, 'Employee')], default=2, max_length=10),
        ),
    ]
