# Generated by Django 4.0.4 on 2022-04-29 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iSmartcoApp', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id_num',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='job_card_requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iSmartcoApp.clientuser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'sysAdmin'), (2, 'CompAdmin'), (3, 'Client'), (4, 'Employee')], default=2),
        ),
    ]
