# Generated by Django 4.0.3 on 2022-05-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iSmartcoApp', '0004_alter_employee_employee_id_num'),
        ('iSmartcoApp', '0005_alter_company_created_by_and_more'),
    ]

    operations = [
    ]
