# Generated by Django 4.0.3 on 2022-05-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iSmartcoApp', '0006_merge_20220503_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_company',
        ),
    ]
