# Generated by Django 4.0.3 on 2022-05-04 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iSmartcoApp', '0007_remove_employee_employee_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clientuser',
            name='company',
        ),
        migrations.AddField(
            model_name='clientuser',
            name='works_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iSmartcoApp.client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'sysAdmin'), (2, 'CompanyAdmin'), (3, 'Client'), (4, 'Employee')], default=2),
        ),
    ]
