# Generated by Django 4.0.3 on 2022-05-17 13:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iSmartcoApp', '0009_phone_remove_employee_id_address_buildingname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='job_card_technicians',
            new_name='job_card_employees',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='job_card_type',
        ),
        migrations.RemoveField(
            model_name='jobcardcategory',
            name='owned_by',
        ),
        migrations.AddField(
            model_name='clientuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcard',
            name='job_card_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iSmartcoApp.jobcardcategory'),
        ),
        migrations.AddField(
            model_name='jobcardcategory',
            name='company_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iSmartcoApp.company'),
        ),
        migrations.AddField(
            model_name='materialused',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialused',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='job_card_priority',
            field=models.CharField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobcardcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
