# Generated by Django 4.0.3 on 2022-05-19 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iSmartcoApp', '0010_rename_job_card_technicians_jobcard_job_card_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='belongs_to',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='job_card_employees',
            field=models.ManyToManyField(blank=True, null=True, related_name='job_card_technicians', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='job_card_status',
            field=models.IntegerField(blank=True, choices=[(1, 'New'), (2, 'Accepted'), (3, 'Travelling to Site'), (4, 'In Progress'), (5, 'Paused'), (6, 'Completed'), (7, 'Cancelled')], default=1, max_length=100, null=True),
        ),
    ]
