# Generated by Django 4.0.3 on 2022-05-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iSmartcoApp', '0011_address_is_personal_alter_address_belongs_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='job_card_status',
            field=models.IntegerField(blank=True, choices=[(1, 'New'), (2, 'Accepted'), (3, 'Travelling to Site'), (4, 'In Progress'), (5, 'Paused'), (6, 'Completed'), (7, 'Cancelled')], default=1, null=True),
        ),
    ]
