# Generated by Django 4.0.3 on 2022-05-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iSmartcoApp', '0012_alter_jobcard_job_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
