# Generated by Django 4.0.3 on 2022-05-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iSmartcoApp', '0014_alter_jobcard_job_card_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='job_card_priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=2),
        ),
    ]
