# Generated by Django 4.0.3 on 2022-05-26 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iSmartcoApp', '0015_alter_jobcard_job_card_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='job_card_employees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
